import Head from "next/head"
import { DemoComponent } from "../components/DemoComponent"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instant Bandit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.description}>Welcome to Instant Bandit</h1>
        <p>
          <DemoComponent preserveSession={false}>
            {(props) => (
              <button
                className={styles.title}
                style={{ background: props.variant === "A" ? "red" : "green" }}
              >
                👉 Click me 👈
              </button>
            )}
          </DemoComponent>
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="/api/hello" target="_blank">
          Is the API working?
        </a>
      </footer>
    </div>
  )
}
